Resources:
  NotifyHandlerServiceRoleC086619B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SendEmailCdkStack/NotifyHandler/ServiceRole/Resource
  NotifyHandlerServiceRoleDefaultPolicyF43613B9:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ses:SendEmail
              - ses:SendRawEmail
              - ses:SendTemplatedEmail
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ses:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :identity/ericflores108@outlook.com
        Version: "2012-10-17"
      PolicyName: NotifyHandlerServiceRoleDefaultPolicyF43613B9
      Roles:
        - Ref: NotifyHandlerServiceRoleC086619B
    Metadata:
      aws:cdk:path: SendEmailCdkStack/NotifyHandler/ServiceRole/DefaultPolicy/Resource
  NotifyHandlerC80F6179:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 68dd5de982ff274baf258199b14462f7729c79642059fe4d2705cc5dc86d40b5.zip
      Role:
        Fn::GetAtt:
          - NotifyHandlerServiceRoleC086619B
          - Arn
      FunctionName: notify-email-ses
      Handler: notify.handler
      Runtime: python3.7
    DependsOn:
      - NotifyHandlerServiceRoleDefaultPolicyF43613B9
      - NotifyHandlerServiceRoleC086619B
    Metadata:
      aws:cdk:path: SendEmailCdkStack/NotifyHandler/Resource
      aws:asset:path: asset.68dd5de982ff274baf258199b14462f7729c79642059fe4d2705cc5dc86d40b5
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWNUQ6CMBBEz8J/WUHiAYTEXwkegJRScQVaw25jSMPdpSV+zcxLZuYMlwyyRH4pVf2YTtiBf7BUo9hR6yc5d70Ef3NGMVojqqf5+02gnME3dtIBR63thGoN8XCboKKVRJoJrkH2DKVTo+ZSkt5EhPvhgGYItbvjj+O4p8m6RcXtypoej8965Zc1pwLyHPLkTYjp4gzjrKE59AeAQQTe0wAAAA==
    Metadata:
      aws:cdk:path: SendEmailCdkStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  api:
    Value:
      Fn::GetAtt:
        - NotifyHandlerC80F6179
        - Arn
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

